# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 958a6aae38c490d70c5a2bfb5b05313edb3e4cf8909ca37d287116406670bd32b7b53f70219343f93686a267cc1d6f8e69b1ab91243ed2409a86ac047bd1fbf5

test:
  secret_key_base: f1a714818b5557207cd8f5671fd6a0004b924b95ad6f0c0dd3501e2fe4d35f888da48e105ca49383f2671dcdd4fbdec97e0a683d6c70221bfea088c724dfe1a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV['GROUVLY_WEBAPP_SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['GROUVLY_WEBAPP_SECRET_KEY_BASE'] %>
